### ISSUE TITLE
Allow for 8 digits to be shown clearly

### ISSUE THREAD

**Issue by nshamit** [ECLK/results-tabulation-ui#77]
**Describe the solution you'd like**
The box count no. is 7 digits long. However, while you can enter it, you can't see the 7 digits clearly. 
Alternatively, the font size within the input box can be reduced as well.

**Comment by RavinduHasithanjana** [comment]
Sherazad this issue was marked in the last Mock election and we fixed this minor issue, we actually not sure about any screen sizes, we actually tried in our screens and below is the screenshot
![WhatsApp Image 2019-10-19 at 18 11 59](https://user-images.githubusercontent.com/17488349/67145139-6d0e8980-f29c-11e9-86ac-a5da1cd717d7.jpeg)
 it actually works.
